ci: remove actions using Rust nightly
Nightly quite often breaks CI by introducing new clippy linters etc,
which disrupts one's work when one wants to land a PR whose CI
suddenly fails for unrelated reasons.

Sometimes, the new linters are also broken and result in false
positives. The one that prompted this commit is a false positive about
needless_return like this:
https://github.com/rust-lang/rust-clippy/issues/13526

```
error: unneeded `return` statement
   --> tests/simulator_tests.rs:212:51
    |
212 |       for simulator_filename in simulator_filenames {
    |  ___________________________________________________^
213 | |         println!("Simulator tests using {}", simulator_filename);
214 | |         let _server = Server::launch(&simulator_filename);
...   |
244 | |         test_btc(&paired_bitbox).await
245 | |     }
```

(there is no return statement)